---
framework: mocha
preRun:
  command:
    - npm install
    - sudo whoami
preMerge:
  pattern:
    - "./test/**/*.js"
postMerge:
  pattern:
    - "./test/**/*.js"
configFile: mocha.opts
version: 1.0
